# Generated by Django 3.0.6 on 2020-06-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collages',
            fields=[
                ('Id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Credit', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('StartClass', models.IntegerField(max_length=1)),
                ('EndClass', models.IntegerField(max_length=1)),
                ('Times', models.IntegerField()),
                ('Place', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Majorities',
            fields=[
                ('Id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Collages')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('Id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('PasswordMd5', models.CharField(max_length=32)),
                ('Description', models.TextField()),
                ('Super', models.BooleanField()),
                ('Collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Collages')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('PasswordMd5', models.CharField(max_length=32)),
                ('Description', models.TextField()),
                ('Majority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Majorities')),
            ],
        ),
        migrations.CreateModel(
            name='StuCse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed', models.BooleanField()),
                ('Score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Courses')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Students')),
            ],
        ),
        migrations.CreateModel(
            name='MajCse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Courses')),
                ('Majority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Majorities')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModel.Teachers'),
        ),
    ]
